app = "agapevendingmachine"
primary_region = "lax"  # Cambié la región a LAX

[build]
  dockerfile = "Dockerfile"  # Esto usa tu Dockerfile para construir la app

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
  [services.http_checks]
  http_path = "/"
  host = "agapevendingmachines.com"
