# fly.toml app configuration file generated for agapevendingmachine-hidden-sound-7269 on 2025-03-30T19:02:08-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agapevendingmachine-hidden-sound-7269'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 0
  ports = []

  [[services.http_checks]]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
